// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: db.sql

package database

import (
	"context"
)

const truncateAllTables = `-- name: TruncateAllTables :exec
TRUNCATE TABLE users, chirps, refresh_tokens
`

func (q *Queries) TruncateAllTables(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateAllTables)
	return err
}
